title: Axel Zúñiga Hernández – Cybersecurity Portfolio
description: Welcome to my cybersecurity portfolio, a collection of projects that showcase my expertise in penetration testing, ethical hacking, and digital security.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
